snapshot 2025-11-07T15:54:02.872013+00:00

diff --git a/scripts/xdg-open.in b/scripts/xdg-open.in
--- a/scripts/xdg-open.in
+++ b/scripts/xdg-open.in
@@ -27,56 +27,18 @@ cat << '_USAGE'
 _USAGE
 }
 
+XDG_UTILS_ENABLE_DOUBLE_HYPEN="y"
+
 #@xdg-utils-common@
 
-# This handles backslashes but not quote marks.
-last_word()
-{
-    # Backslash handling is intended, not using `first` too
-    # shellcheck disable=SC2162,SC2034
-    read first rest
-    echo "$rest"
-}
-
-# Get the value of a key in a desktop file's Desktop Entry group.
-# Example: Use get_key foo.desktop Exec
-# to get the values of the Exec= key for the Desktop Entry group.
-get_key()
-{
-    local file="${1}"
-    local key="${2}"
-    local desktop_entry=""
-
-    IFS_="${IFS}"
-    IFS=""
-    # No backslash handling here, first_word and last_word do that
-    while read -r line
-    do
-        case "$line" in
-            "[Desktop Entry]")
-                desktop_entry="y"
-            ;;
-            # Reset match flag for other groups
-            "["*)
-                desktop_entry=""
-            ;;
-            "${key}="*)
-                # Only match Desktop Entry group
-                if [ -n "${desktop_entry}" ]
-                then
-                    echo "${line}" | cut -d= -f 2-
-                fi
-        esac
-    done < "${file}"
-    IFS="${IFS_}"
-}
-
+# (string_that_may_be_an_url)
 has_url_scheme()
 {
 	echo "$1" | LC_ALL=C grep -Eq '^[[:alpha:]][[:alpha:][:digit:]+\.\-]*:'
 }
 
 # Returns true if argument is a file:// URL or path
+# (url_or_path)
 is_file_url_or_path()
 {
     if echo "$1" | grep -q '^file://' || ! has_url_scheme "$1" ; then
@@ -86,6 +48,7 @@ is_file_url_or_path()
     fi
 }
 
+# ()
 get_hostname() {
     if [ -z "$HOSTNAME" ]; then
         if command -v hostname > /dev/null; then
@@ -98,6 +61,7 @@ get_hostname() {
 
 # If argument is a file URL, convert it to a (percent-decoded) path.
 # If not, leave it as it is.
+# (file_url)
 file_url_to_path()
 {
     local file="$1"
@@ -121,6 +85,7 @@ file_url_to_path()
     echo "$file"
 }
 
+# (url_or_path)
 open_cygwin()
 {
     cygstart "$1"
@@ -132,6 +97,7 @@ open_cygwin()
     fi
 }
 
+# (url_or_path)
 open_darwin()
 {
     open "$1"
@@ -143,6 +109,7 @@ open_darwin()
     fi
 }
 
+# (url_or_path)
 open_kde()
 {
     if [ -n "${KDE_SESSION_VERSION}" ]; then
@@ -155,6 +122,12 @@ open_kde()
         ;;
         6)
           kde-open "$1"
+        ;;
+        *)
+	      DEBUG 0 "Detected an unknown KDE version using the KDE_SESSION_VERSION environment variable."
+	      DEBUG 1 "If you are on something newer than Plasma 6 you are likely running an outdated version of the xdg-utils, please check for updates."
+	      DEBUG 0 "Falling back to the generic opener."
+	      open_generic "$1"
         ;;
       esac
     else
@@ -169,6 +142,7 @@ open_kde()
     fi
 }
 
+# (url_or_path)
 open_deepin()
 {
     if dde-open -version >/dev/null 2>&1; then
@@ -184,6 +158,7 @@ open_deepin()
     fi
 }
 
+# (url_or_path)
 open_gnome3()
 {
     if gio help open 2>/dev/null 1>&2; then
@@ -201,6 +176,7 @@ open_gnome3()
     fi
 }
 
+# (url_or_path)
 open_gnome()
 {
     if gio help open 2>/dev/null 1>&2; then
@@ -220,6 +196,7 @@ open_gnome()
     fi
 }
 
+# (url_or_path)
 open_mate()
 {
     if gio help open 2>/dev/null 1>&2; then
@@ -239,9 +216,12 @@ open_mate()
     fi
 }
 
+# (url_or_path)
 open_xfce()
 {
-    if exo-open --help 2>/dev/null 1>&2; then
+    if xfce-open --help 2>/dev/null 1>&2; then
+        xfce-open "$1"
+    elif exo-open --help 2>/dev/null 1>&2; then
         exo-open "$1"
     elif gio help open 2>/dev/null 1>&2; then
         gio open "$1"
@@ -258,6 +238,7 @@ open_xfce()
     fi
 }
 
+# (url_or_path)
 open_enlightenment()
 {
     if enlightenment_open --help 2>/dev/null 1>&2; then
@@ -273,7 +254,8 @@ open_enlightenment()
     fi
 }
 
-open_flatpak()
+# (url_or_path)
+open_gdbus()
 {
     if is_file_url_or_path "$1"; then
         local file
@@ -308,7 +290,353 @@ open_flatpak()
 #-----------------------------------------
 # Recursively search .desktop file
 
-#(application, directory, target file, target_url)
+awk_script_open_with_desktop_file="$(cat << 'AWKEOF'
+BEGIN {
+
+	debug_level = ENVIRON["XDG_UTILS_DEBUG_LEVEL"]
+
+	if (uri_arg) {
+		split(uri_arg, split_uri_arg, " ")
+	}
+
+	has_uri = 0;
+	filec = 0;
+	for (i=1; split_uri_arg[i]; i++) {
+		has_uri = 1;
+		uri = split_uri_arg[i]
+		uris[i-1] = uri;
+		debug(2, "URI: " uri)
+		if (file_arg != "") {
+			file = decode_local_file_uri(uri)
+			if (file) {
+				debug(2, "File: " file)
+				files[filec] = file;
+				filec = filec + 1;
+			}
+		}
+	}
+
+	if (file_arg != "") {
+		debug(2, "File: " file_arg)
+		files[filec] = file_arg;
+		filec = filec + 1;
+		if (!has_uri) {
+			debug(2, "URI (falling back to file path): " file_arg)
+			uris[0] = file_arg
+		}
+	}
+	
+	in_main_section = 0;
+
+	exec_value = 0;
+	icon_value = 0;
+	name_value = 0;
+}
+
+/^\[/ {
+	in_main_section = 0;
+}
+
+$0 == "[Desktop Entry]" {
+	in_main_section = 1
+}
+
+function unescape_value(escaped) {
+	value = ""
+	for (i=1; i<=length(escaped); i++) {
+		char = substr(escaped, i, 1)
+		if (char == "\\") {
+			i = i+1
+			next_char = substr(escaped,i,1);
+			if (next_char == "s") {
+				value = value " ";
+			} else if (next_char == "n") {
+				value = value "\n";
+			} else if (next_char == "t") {
+				value = value "\t";
+			} else if (next_char == "r") {
+				value = value "\r";
+			} else if (next_char == "\\") {
+				value = value "\\";
+			}
+		} else {
+			value = value char
+		}
+	}
+	return value;
+}
+
+function split_exec_value(value, out_args) {
+	argc = 0;
+	in_quote = 0;
+	current_arg = "";
+	next_is_literal = 0;
+	for (i=1; i<=length(value); i++) {
+		char = substr(value,i,1)
+		if (next_is_literal) {
+			next_is_literal = 0;
+			current_arg = current_arg char
+			continue
+		}
+		if (in_quote) {
+			if (char == "\"") {
+				in_quote = 0;
+				out_args[argc] = current_arg;
+				argc = argc + 1;
+				current_arg = "";
+			} else if (char == "\\") {
+				next_is_literal = 1;
+			} else {
+				current_arg = current_arg char
+			}
+		} else {
+			if (current_arg == "" && char == "\"") {
+				in_quote = 1;
+			} else if (char != " ") {
+				current_arg = current_arg char
+			} else if (current_arg != "") {
+				out_args[argc] = current_arg;
+				argc = argc + 1;
+				current_arg = "";
+			}
+		}
+	}
+	if (current_arg != "") {
+		out_args[argc] = current_arg;
+	}
+}
+
+function hex_value(char) {
+	value = char - "0";
+	if (value >= 0 && value < 10) {
+		return value;
+	}
+	value = char - "a";
+	if (value >= 10 && value < 16) {
+		return value;
+	}
+	value = char - "A";
+	if (value >= 10 && value < 16) {
+		return value;
+	}
+	return 0;
+}
+
+function uri_decode(text) {
+	output = ""
+	for (i=1; i<=length(text); i++) {
+		char = substr(text, i, 1);
+		if (char != "%") {
+			output = output char;
+			continue
+		}
+		char_a = substr(text, i+1, 1);
+		char_b = substr(text, i+2, 1);
+		i = i+2;
+		numeric = hex_value(char_a)*16+hex_value(char_b);
+		if (numeric != 0 && numeric != 47) {
+			output = output sprintf("%c", numeric)
+		}
+	}
+	return output;
+}
+
+function decode_local_file_uri(uri) {
+	if (!match(uri, /^file:\/\//)) {
+		return 0;
+	}
+	host = ""
+	path = 0
+	slash_count = 0
+	host_start = 0
+	host_end = 0
+	path_start = 0
+	for (i=1; i<=length(uri); i++) {
+		char = substr(text, i, 1);
+		if (char == "/") {
+			slash_count++;
+			if (slash_count == 2) {
+				host_start = i;
+			}
+			if (slash_count == 3) {
+				path_start = i;
+			}
+			continue
+		} else if (host_start && char == ":") {
+			host_end = i;
+		} else if (char == "?" || char == "#") {
+			if (path_start) {
+				path = substr(uri, path_start, i - path_start)
+			}
+			# ignore that we wouldn't fully parse the hostname in this case,
+			# if the hostname isn't finished here it'll fail anyway.
+			break
+		}
+		if (host_start && host_end) {
+			host = substr(uri, host_start, host_end - host_start);
+		}
+	}
+	# Hostname must either be empty, "localhost" or match local hostname
+	if (host != "" && host != "localhost" && host != hostname) {
+		return 0;
+	}
+	if (path) {
+		return uri_decode(path)
+	}
+	return 0;
+}
+
+function debug(level, text) {
+	if (!debug_level) {
+		return;
+	}
+	if (level <= debug_level) {
+		print "DEBUG: " text >> "/dev/stderr";
+	}
+}
+
+function error(text) {
+	printf("err\0");
+	print "xdg-open ERROR: " text >> "/dev/stderr";
+	exit 4
+}
+
+in_main_section && match($0, /^[^#=\[]+\[?[^=\]]*\]?=/) {
+	index_of_eq = index($0, "=");
+	index_of_bracket_open = index($0, "[");
+	if (index_of_bracket_open && index_of_bracket_open < index_of_eq) {
+		key = substr($0, 1, index_of_bracket_open-1)
+		local = substr($0, index_of_bracket_open+1, index_of_eq-index_of_bracket_open-2);
+	} else {
+		key = substr($0, 1, index_of_eq-1);
+		local = "";
+	}
+	value = substr($0, index_of_eq+1);
+	debug(4, "Key: " key " Local: " local " Value: " value);
+	if (key == "Exec") {
+		exec_value = unescape_value(value);
+	} else if (key == "Icon") {
+		icon_value = unescape_value(value);
+	} else if (key == "Name") {
+		# TODO: handle actual localization
+		if (local == "") {
+			name_value = unescape_value(value)
+		}
+	}
+}
+
+END {
+	if (!exec_value) {
+		print "xdg-open: No Exec= line found in main section of desktop file!" >> "/dev/stderr";
+		exit 1;
+	}
+	debug(2, "Unescaped: " exec_value)
+	split_exec_value(exec_value, args)
+	# Field code expansion
+	expanded_args[0] = "";
+	eargc = 0;
+	found_file_field_codes = 0;
+	for (i=0; args[i]; i++) {
+		arg = args[i];
+		debug(2, "Running field code expansion on arg: " arg);
+		if (arg == "%F") {
+			for (j=0; j<length(files); j++) {
+				expanded_args[eargc] = files[j];
+				eargc = eargc + 1;
+			}
+			found_file_field_codes++;
+			continue
+		} else if (arg == "%U") {
+			for (j=0; j<length(uris); j++) {
+				expanded_args[eargc] = uris[j];
+				eargc = eargc + 1;
+			}
+			found_file_field_codes++;
+			continue
+		} else if (arg == "%i") {
+			if (icon_value) {
+				expanded_args[eargc] = "--icon"
+				expanded_args[eargc] = icon_value
+				eargc = eargc + 1;
+			}
+			continue
+		}
+		debug(2, "Trying to find in-text field code ...");
+		expanded_arg = ""
+		for (j=1; j<=length(arg); j++) {
+			char = substr(arg,j,1);
+			if (char != "%") {
+				expanded_arg = expanded_arg char
+				continue
+			}
+			j = j+1;
+			char = substr(arg,j,1);
+			debug(2, "Found field code expansion: %" char);
+			if (char == "%") {
+				expanded_arg = expanded_arg "%"
+			} else if (char == "f") {
+				# Take just the first arg for the prototype
+				expanded_arg = expanded_arg files[0];
+				found_file_field_codes++;
+			} else if (char == "u") {
+				# Take just the first arg for the prototype
+				expanded_arg = expanded_arg uris[0];
+				found_file_field_codes++;
+			} else if (char == "c") {
+				if (name_value) {
+					expanded_arg = expanded_arg name_value
+				}
+			} else if (char == "k") {
+				# Location of desktop file either as URI or local filename
+				# Ignore for now
+				# TODO
+			} else if (char == "d" || char == "D" || char == "n" || char == "N") {
+				# Deprecated, silently remove
+			} else if (char == "i" || char == "U" || char == "F") {
+				error("xdg-open: Field code %" char "must be stand alone as it expands into multiple arguments!")
+			} else {
+				error("xdg-open: Unknown field code: %" char " in Exec key!");
+			}
+		}
+		if (found_file_field_codes > 1) {
+			error("xdg-open: More than one file field codes (%f, %F, %u, %U) in Exec key, this .desktop file is invalid!");
+		}
+		expanded_args[eargc] = expanded_arg;
+		eargc = eargc + 1;
+	}
+
+	if (found_file_field_codes == 0) {
+		debug(1, "Didn't find a file field code (%f, %F, %u, %U), appending filepath/url as last argument");
+		if (files[0]) {
+			expanded_args[eargc] = files[0];
+		} else {
+			expanded_args[eargc] = uris[0];
+		}
+		eargc = eargc + 1;
+	}
+
+	printf("cmd\0");
+	for (i=0; expanded_args[i]; i++) {
+		debug(1, "Arg: " expanded_args[i]);
+		printf("%s\0", expanded_args[i]);
+	}
+	exit
+}
+AWKEOF
+)"
+
+
+# (desktop_file, file, uri (optional))
+open_with_desktop_file()
+{
+	# shellcheck disable=SC2016 # Not expanding is intended here
+	awk -v"hostname=$(get_hostname)" -v"file_arg=$2" -v"uri_arg=$3" "$awk_script_open_with_desktop_file" < "$1" | xargs -0 -x sh -c 'if [ "$1" = "cmd" ] ; then shift; exec "$@" ; else exit 4 ; fi' -
+	if [ "$?" -eq 123 ] ; then
+		exit_failure_operation_failed
+	fi
+}
+
+#(application, directory, target_file, target_url (optional))
 search_desktop_file()
 {
     local default="$1"
@@ -325,62 +653,8 @@ search_desktop_file()
     fi
 
     if [ -r "$file" ] ; then
-        command="$(get_key "${file}" "Exec" | first_word)"
-        if command -v "$command" >/dev/null; then
-            icon="$(get_key "${file}" "Icon")"
-            # FIXME: Actually LC_MESSAGES should be used as described in
-            # http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s04.html
-            localised_name="$(get_key "${file}" "Name")"
-            #shellcheck disable=SC2046 # Splitting is intentional here
-            set -- $(get_key "${file}" "Exec" | last_word)
-            # We need to replace any occurrence of "%f", "%F" and
-            # the like by the target file. We examine each
-            # argument and append the modified argument to the
-            # end then shift.
-            local args=$#
-            local replaced=0
-            while [ $args -gt 0 ]; do
-                case $1 in
-                    %[c])
-                        replaced=1
-                        arg="${localised_name}"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                    %[fF])
-	                    # if there is only a target_url return,
-	                    # this application can't handle it.
-	                    [ -n "$target" ] || return
-                        replaced=1
-                        arg="$target"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                    %[uU])
-                        replaced=1
-                        # When an URI is requested use it,
-                        # otherwise fall back to the filepath.
-                        arg="${target_uri:-$target}"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                    %[i])
-                        replaced=1
-                        shift
-                        set -- "$@" "--icon" "$icon"
-                        ;;
-                    *)
-                        arg="$1"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                esac
-                args=$(( args - 1 ))
-            done
-            [ $replaced -eq 1 ] || set -- "$@" "${target:-$target_uri}"
-            env "$command" "$@"
-            exit_success
-        fi
+		open_with_desktop_file "$file" "$target" "$target_uri"
+		exit_success
     fi
 
     for d in "$dir/"*/; do
@@ -411,6 +685,8 @@ open_generic_xdg_mime()
     fi
 }
 
+# Open an url using the x-scheme-handler/<scheme> dummy mimetype
+# (url)
 open_generic_xdg_x_scheme_handler()
 {
     scheme="$(echo "$1" | LC_ALL=C sed -n 's/\(^[[:alpha:]][[:alnum:]+\.-]*\):.*$/\1/p')"
@@ -420,11 +696,15 @@ open_generic_xdg_x_scheme_handler()
     fi
 }
 
+# (args ...)
 has_single_argument()
 {
   test $# = 1
 }
 
+# Open an url or path using the BROWSER variable.
+# Exits on success retuerns otherwise.
+# (url_or_path)
 open_envvar()
 {
     local oldifs="$IFS"
@@ -455,6 +735,7 @@ open_envvar()
     done
 }
 
+# (url_or_path)
 open_wsl()
 {
     local win_path
@@ -474,6 +755,7 @@ open_wsl()
     fi
 }
 
+# (url_or_path)
 open_generic()
 {
     if is_file_url_or_path "$1"; then
@@ -486,7 +768,11 @@ open_generic()
             filetype="$(xdg-mime query filetype "$file" | sed "s/;.*//")"
             # passing a path a url is okay too,
             # see desktop file specification for '%u'
-            open_generic_xdg_mime "$file" "$filetype" "$1"
+			if has_url_scheme "$1" ; then
+				open_generic_xdg_mime "$file" "$filetype" "$1"
+			else
+				open_generic_xdg_mime "$file" "$filetype"
+			fi
         fi
 
         if command -v run-mailcap >/dev/null; then
@@ -525,6 +811,7 @@ open_generic()
     exit_failure_operation_impossible "no method available for opening '$1'"
 }
 
+# (url_or_path)
 open_lxde()
 {
 
@@ -550,6 +837,7 @@ open_lxde()
     fi
 }
 
+# (url_or_path)
 open_lxqt()
 {
     if qtxdg-mat open --help 2>/dev/null 1>&2; then
@@ -565,30 +853,73 @@ open_lxqt()
     fi
 }
 
-[ x"$1" != x"" ] || exit_failure_syntax
+open_one_argument()
+{
+    url="$1"
+    case "$DE" in
+        kde)
+            open_kde "$url"
+            ;;
 
-url=
-while [ $# -gt 0 ] ; do
-    parm="$1"
-    shift
+        deepin)
+            open_deepin "$url"
+            ;;
 
-    case "$parm" in
-      -*)
-        exit_failure_syntax "unexpected option '$parm'"
-        ;;
+        gnome3|cinnamon)
+            open_gnome3 "$url"
+            ;;
 
-      *)
-        if [ -n "$url" ] ; then
-            exit_failure_syntax "unexpected argument '$parm'"
-        fi
-        url="$parm"
-        ;;
+        gnome)
+            open_gnome "$url"
+            ;;
+
+        mate)
+            open_mate "$url"
+            ;;
+
+        xfce)
+            open_xfce "$url"
+            ;;
+
+        lxde)
+            open_lxde "$url"
+            ;;
+
+        lxqt)
+            open_lxqt "$url"
+            ;;
+
+        enlightenment)
+            open_enlightenment "$url"
+            ;;
+
+        cygwin)
+            open_cygwin "$url"
+            ;;
+
+        darwin)
+            open_darwin "$url"
+            ;;
+
+        flatpak|toolbx)
+            open_gdbus "$url"
+            ;;
+
+        wsl)
+            open_wsl "$url"
+            ;;
+
+        generic)
+            open_generic "$1"
+            ;;
+
+        *)
+            exit_failure_operation_impossible "no method available for opening '$1'"
+            ;;
     esac
-done
+}
 
-if [ -z "${url}" ] ; then
-    exit_failure_syntax "file or URL argument missing"
-fi
+[ x"$1" != x"" ] || exit_failure_syntax
 
 detectDE
 
@@ -608,64 +939,52 @@ case "${BROWSER}" in
         ;;
 esac
 
-case "$DE" in
-    kde)
-    open_kde "$url"
-    ;;
+# Handle the URL arguments and script-specific options.
+NOWAIT=0
+err=0
 
-    deepin)
-    open_deepin "$url"
-    ;;
+# (arg, remaining_args)
+handle_positional_arg() {
+	echo "remaining: $2"
+	if [ "$2" -gt 0 ] || [ "$NOWAIT" = 1 ]; then
+		(open_one_argument "$1" &)
+	else
+		(open_one_argument "$1")
+	fi
+	this_err=$?
+	if [ $err -eq 0 ]; then
+		err=$this_err
+	fi
+}
 
-    gnome3|cinnamon)
-    open_gnome3 "$url"
-    ;;
+while [ $# -gt 0 ]; do
+    parm="$1"
+    shift
 
-    gnome)
-    open_gnome "$url"
-    ;;
+    case "$parm" in
+        --nowait)
+            NOWAIT=1
+            ;;
 
-    mate)
-    open_mate "$url"
-    ;;
+		--)
+			break
+			;;
 
-    xfce)
-    open_xfce "$url"
-    ;;
+        -*)
+            exit_failure_syntax "unexpected option '$parm'"
+            ;;
 
-    lxde)
-    open_lxde "$url"
-    ;;
+        *)
+	        handle_positional_arg "$parm" "$#"
+            ;;
+    esac
+done
 
-    lxqt)
-    open_lxqt "$url"
-    ;;
+# handle positional arguments after a --
+while [ $# -gt 0 ]; do
+	parm="$1"
+	shift
+	handle_positional_arg "$parm" "$#"
+done
 
-    enlightenment)
-    open_enlightenment "$url"
-    ;;
-
-    cygwin)
-    open_cygwin "$url"
-    ;;
-
-    darwin)
-    open_darwin "$url"
-    ;;
-
-    flatpak)
-    open_flatpak "$url"
-    ;;
-
-    wsl)
-    open_wsl "$url"
-    ;;
-
-    generic)
-    open_generic "$url"
-    ;;
-
-    *)
-    exit_failure_operation_impossible "no method available for opening '$url'"
-    ;;
-esac
+exit $err
diff --git a/scripts/xdg-settings.in b/scripts/xdg-settings.in
--- a/scripts/xdg-settings.in
+++ b/scripts/xdg-settings.in
@@ -26,6 +26,9 @@ _USAGE
 
 #@xdg-utils-common@
 
+# Tests if the given text is a *.desktop file name.
+# Exits with an error message if not, returns if it is.
+# (passible_desktop_file_name)
 check_desktop_filename()
 {
     case "$1" in
@@ -52,6 +55,7 @@ check_desktop_filename()
 # MIME type. (We can't just delete the local version, since the user may have
 # made other changes to it as well. So, tweak the existing file.)
 # This function is hard-coded for text/html but it could be adapted if needed.
+# (desktop_file_name, mimetype)
 fix_local_desktop_file()
 {
     if test -z "$2" ; then
@@ -91,6 +95,7 @@ fix_local_desktop_file()
 # }}} utility functions
 # {{{ MIME utilities
 
+# ()
 xdg_mime_fixup()
 {
     # xdg-mime may use ktradertest, which will fork off a copy of kdeinit if
@@ -105,6 +110,8 @@ xdg_mime_fixup()
     fi
 }
 
+# Query the desktop file of the browser (or for a given mimetype)
+# (mimetype (or empty))
 get_browser_mime()
 {
     if test -z "$1" ; then
@@ -116,6 +123,8 @@ get_browser_mime()
     xdg-mime query default "$MIME"
 }
 
+# Set the handler for the browser or a given mimetype
+# (desktop_file_name, mimtype (or empty))
 set_browser_mime()
 {
     xdg_mime_fixup
@@ -141,6 +150,7 @@ set_browser_mime()
 # {{{ KDE utilities
 
 # Reads the KDE configuration setting, compensating for a bug in some versions of kreadconfig.
+# (configurtion_file, section, key)
 read_kde_config()
 {
     configfile="$1"
@@ -174,6 +184,7 @@ read_kde_config()
 
 # Resolves the KDE browser setting to a binary: if prefixed with !, simply removes it;
 # otherwise, uses desktop_file_to_binary to get the binary out of the desktop file.
+# ()
 resolve_kde_browser()
 {
     [ -z "$browser" ] && return
@@ -189,6 +200,7 @@ resolve_kde_browser()
 
 # Does the opposite of resolve_kde_browser: if prefixed with !, tries to find a desktop
 # file corresponding to the binary, otherwise just returns the desktop file name.
+# ()
 resolve_kde_browser_desktop()
 {
     [ -z "$browser" ] && return
@@ -203,6 +215,7 @@ resolve_kde_browser_desktop()
     esac
 }
 
+# ()
 read_kde_browser()
 {
     # since Plasma >= 5.19
@@ -215,6 +228,7 @@ read_kde_browser()
     echo $ret
 }
 
+# ()
 get_browser_kde()
 {
     browser="`read_kde_browser`"
@@ -226,6 +240,7 @@ get_browser_kde()
     fi
 }
 
+# (desktop_file_name)
 check_browser_kde()
 {
     check="`desktop_file_to_binary "$1"`"
@@ -259,6 +274,7 @@ check_browser_kde()
     exit_success
 }
 
+# (desktop_file_name)
 set_browser_kde()
 {
     # Set the default browser.
@@ -280,11 +296,25 @@ set_browser_kde()
 # }}} KDE
 # {{{ Deepin
 
+# ()
 read_deepin_browser()
 {
-    dbus-send --print-reply=literal --dest=com.deepin.daemon.Mime /com/deepin/daemon/Mime com.deepin.daemon.Mime.GetDefaultApp string:"x-scheme-handler/http" | jq -r '.Id'
+    # since deepin 23, there is no GetDefaultApp method, we use mime to read
+    ret="$(get_browser_mime "x-scheme-handler/http")"
+    if [ -z "$ret" ]; then
+        # older deepin versions
+        dbus-send --print-reply=literal --dest=com.deepin.daemon.Mime /com/deepin/daemon/Mime com.deepin.daemon.Mime.GetDefaultApp string:"x-scheme-handler/http" | jq -r '.Id'
+        if [ $? -ne 0 ]; then
+            exit_failure_operation_failed
+        else
+            exit_success
+        fi
+    fi
+
+    echo "$ret"
 }
 
+# ()
 get_browser_deepin()
 {
     browser="$(read_deepin_browser)"
@@ -296,15 +326,22 @@ get_browser_deepin()
     fi
 }
 
+# (desktop_file_name)
 check_browser_deepin()
 {
     if [ "$(read_deepin_browser)" = "$1" ]; then
+        echo yes
         exit_success
     else
+        echo no
         exit_failure_operation_failed
     fi
+
+    exit_success
+    echo yes
 }
 
+# (desktop_file_name)
 set_browser_deepin()
 {
     xdg-mime default "$1" x-scheme-handler/http x-scheme-handler/ftp x-scheme-handler/https text/html text/xml text/xhtml_xml text/xhtml+xml
@@ -318,6 +355,7 @@ set_browser_deepin()
 # }}} Deepin
 # {{{ GNOME
 
+# ()
 get_browser_gnome()
 {
     binary="`gconftool-2 --get /desktop/gnome/applications/browser/exec | first_word`"
@@ -333,6 +371,7 @@ get_browser_gnome()
     fi
 }
 
+# (desktop_file_name)
 check_browser_gnome()
 {
     check="`desktop_file_to_binary "$1"`"
@@ -363,6 +402,7 @@ check_browser_gnome()
     exit_success
 }
 
+# (desktop_file_name)
 set_browser_gnome()
 {
     binary="`desktop_file_to_binary "$1"`"
@@ -388,11 +428,13 @@ set_browser_gnome()
 # }}} GNOME
 # {{{ GNOME 3.x
 
+# ()
 get_browser_gnome3()
 {
     get_browser_mime "x-scheme-handler/http"
 }
 
+# (desktop_file_name)
 check_browser_gnome3()
 {
     desktop="$1"
@@ -413,6 +455,7 @@ check_browser_gnome3()
     exit_success
 }
 
+# (desktop_file_name)
 set_browser_gnome3()
 {
     binary="`desktop_file_to_binary "$1"`"
@@ -427,6 +470,7 @@ set_browser_gnome3()
 # }}} GNOME 3.x
 # {{{ LXQt
 
+# ()
 get_browser_lxqt()
 {
     if qtxdg-mat def-web-browser --help 2> /dev/null 1>&2; then
@@ -436,6 +480,7 @@ get_browser_lxqt()
     fi
 }
 
+# (desktop_file_name)
 check_browser_lxqt()
 {
     desktop="$1"
@@ -456,6 +501,7 @@ check_browser_lxqt()
     fi
 }
 
+# (desktop_file_name)
 set_browser_lxqt()
 {
     binary="`desktop_file_to_binary "$1"`"
@@ -470,6 +516,7 @@ set_browser_lxqt()
 # }}} LXQt
 # {{{ xfce
 
+# ()
 get_browser_xfce()
 {
     search="${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
@@ -487,6 +534,7 @@ get_browser_xfce()
     exit_failure_operation_failed
 }
 
+# (desktop_file_name)
 check_browser_xfce()
 {
     browser="`get_browser_xfce`"
@@ -498,6 +546,7 @@ check_browser_xfce()
     exit_success
 }
 
+# (desktop_file_name)
 check_xfce_desktop_file()
 {
     # Annoyingly, xfce wants its .desktop files in a separate directory instead
@@ -538,6 +587,7 @@ check_xfce_desktop_file()
     return 1
 }
 
+# (desktop_file_name)
 set_browser_xfce()
 {
     check_xfce_desktop_file "$1" || exit_failure_operation_failed
@@ -571,18 +621,20 @@ set_browser_xfce()
 # }}} xfce
 # {{{ generic
 
+# (mimetype (or empty))
 get_browser_generic()
 {
-    if [ -n "$BROWSER" ]; then
+
+    if get_browser_mime "${1:-x-scheme-handler/http}"; then
+        return 0
+    fi
+
+	if [ -n "$BROWSER" ]; then
         local browser=$(binary_to_desktop_file "${BROWSER%%:*}")
         if [ -n "$browser" ]; then
             basename "$browser"
             return 0
         fi
-    fi
-
-    if get_browser_mime x-scheme-handler/http; then
-        return 0
     fi
 
     # Debian and derivatives have x-www-browser
@@ -595,6 +647,7 @@ get_browser_generic()
     return 4
 }
 
+# (desktop_file_name)
 check_browser_generic()
 {
     local desktop="$1"
@@ -621,15 +674,41 @@ check_browser_generic()
     exit_success
 }
 
+# (command_or_path_to_binary)
+normalize_binary()
+{
+	xdg_realpath "$(command -v "$1")"
+}
+
+# The BROWSER variable is outside the control of xdg-settings,
+# the best we can do is to do our part and explain
+# that additional configurtion could be neccessary
+#
+# Takes as argument the value browser is suggested to be set to.
+# (expected_content_of_browser_variable)
+explain_browser_variable()
+{
+	if [ "$(normalize_binary "$1")" != "$(normalize_binary "$BROWSER")" ] ; then
+		echo "\$BROWSER is set and can't be changed with xdg-settings." >&2
+		echo "This means that some applications won't adopt the new browser setting." >&2
+		echo "The \$BROWSER envoirnment variable is likely set in your ~/.profile or ~/.bashrc which you have to edit manually. If you don't find it there consult the documentation/wiki of your desktop envoirnment or distribution." >&2
+		echo "Depending on the applications not setting \$BROWSER at all might also help." >&2
+	    echo "" >&2
+	    echo "Your \$BROWSER is currently set to: $BROWSER" >&2
+	    echo "It should be set to: $1" >&2
+    fi
+}
+
+# (desktop_file_name)
 set_browser_generic()
 {
-    if [ -n "$BROWSER" ]; then
-        exit_failure_operation_failed \
-            "\$BROWSER is set and can't be changed with xdg-settings"
-    fi
 
-    binary=$(desktop_file_to_binary "$1")
-    [ -n "$binary" ] || exit_failure_file_missing
+    binary="$(desktop_file_to_binary "$1")"
+    [ -n "$binary" ] || exit_failure_file_missing "Can't resolve this desktop file name to a command"
+
+    if [ -n "$BROWSER" ] && [ "$binary" != "$BROWSER" ]; then
+        explain_browser_variable "$binary"
+    fi
 
     set_browser_mime "$1" text/html || return
 
@@ -657,6 +736,7 @@ exit_unimplemented_default_handler()
 # default mail handler for the mailto scheme, otherwise we will use the mime
 # type x-scheme-handler/scheme.
 
+# (scheme)
 get_url_scheme_handler_kde()
 {
     if [ "$1" = "mailto" ]; then
@@ -672,6 +752,7 @@ get_url_scheme_handler_kde()
     fi
 }
 
+# (scheme, desktop_file_name)
 check_url_scheme_handler_kde()
 {
     check="`desktop_file_to_binary "$2"`"
@@ -703,6 +784,7 @@ check_url_scheme_handler_kde()
     exit_success
 }
 
+# (scheme, desktop_file_name)
 set_url_scheme_handler_kde()
 {
     set_browser_mime "$2" "x-scheme-handler/$1" || return
@@ -721,6 +803,7 @@ set_url_scheme_handler_kde()
 # }}} KDE
 # {{{ GNOME
 
+# (scheme)
 get_url_scheme_handler_gnome()
 {
     binary="`gconftool-2 --get /desktop/gnome/url-handlers/$1/command | first_word`"
@@ -733,6 +816,7 @@ get_url_scheme_handler_gnome()
     fi
 }
 
+# (scheme, desktop_file_name)
 check_url_scheme_handler_gnome()
 {
     check="`desktop_file_to_binary "$2"`"
@@ -749,6 +833,7 @@ check_url_scheme_handler_gnome()
     exit_success
 }
 
+# (scheme, desktop_file_name)
 set_url_scheme_handler_gnome()
 {
     binary="`desktop_file_to_binary "$2"`"
@@ -762,6 +847,7 @@ set_url_scheme_handler_gnome()
 # }}} GNOME
 # {{{ LXQt
 
+# (scheme)
 get_url_scheme_handler_lxqt()
 {
     if qtxdg-mat defapp --help 2> /dev/null 1>&2; then
@@ -771,6 +857,7 @@ get_url_scheme_handler_lxqt()
     fi
 }
 
+# (scheme, desktop_file_name)
 check_url_scheme_handler_lxqt()
 {
     desktop="$2"
@@ -791,11 +878,11 @@ check_url_scheme_handler_lxqt()
     fi
 }
 
+# (scheme, desktop_file_name)
 set_url_scheme_handler_lxqt()
 {
     binary="`desktop_file_to_binary "$2"`"
     [ "$binary" ] || exit_failure_file_missing
-    set_browser_mime "$2" || return
 
     # Set the default browser.
     set_browser_mime "$2" "x-scheme-handler/$1" || return
@@ -804,11 +891,13 @@ set_url_scheme_handler_lxqt()
 # }}} LXQt
 # {{{ GNOME 3.x
 
+# (scheme)
 get_url_scheme_handler_gnome3()
 {
     get_browser_mime "x-scheme-handler/$1"
 }
 
+# (scheme, desktop_file_name)
 check_url_scheme_handler_gnome3()
 {
     desktop="$2"
@@ -826,6 +915,7 @@ check_url_scheme_handler_gnome3()
     exit_success
 }
 
+# (scheme, desktop_file_name)
 set_url_scheme_handler_gnome3()
 {
     binary="`desktop_file_to_binary "$2"`"
@@ -838,16 +928,19 @@ set_url_scheme_handler_gnome3()
 # }}} GNOME 3.x
 # {{{ xfce
 
+# (scheme)
 get_url_scheme_handler_xfce()
 {
     exit_unimplemented_default_handler "$1"
 }
 
+# (scheme, desktop_file_name)
 check_url_scheme_handler_xfce()
 {
     exit_unimplemented_default_handler "$1"
 }
 
+# (scheme, desktop_file_name)
 set_url_scheme_handler_xfce()
 {
     exit_unimplemented_default_handler "$1"
@@ -856,15 +949,17 @@ set_url_scheme_handler_xfce()
 # }}} xfce
 # {{{ generic
 
+# (scheme)
 get_url_scheme_handler_generic()
 {
     if [ -n "$BROWSER" ] && ([ "$1" = http ] || [ "$1" = https ]); then
-        get_browser_generic
+        get_browser_generic "x-scheme-handler/$1"
     else
         get_browser_mime "x-scheme-handler/$1"
     fi
 }
 
+# (scheme, desktop_file_name)
 check_url_scheme_handler_generic()
 {
     local scheme="$1" desktop="$2"
@@ -874,7 +969,7 @@ check_url_scheme_handler_generic()
         exit_success
     fi
 
-    local browser=$(get_url_scheme_handler_generic "$scheme")
+    local browser="$(get_url_scheme_handler_generic "$scheme")"
     if [ "$browser" != "$desktop" ]; then
         echo no
         exit_success
@@ -883,18 +978,20 @@ check_url_scheme_handler_generic()
     exit_success
 }
 
+# (scheme, desktop_file_name)
 set_url_scheme_handler_generic()
 {
     local scheme="$1" desktop="$2"
 
-    if [ -n "$BROWSER" ] && \
-           ([ "$scheme" = http ] || [ "$scheme" = https ]); then
-        exit_failure_operation_failed \
-            "\$BROWSER is set and can't be changed with xdg-settings"
+    # needed by explain_browser_variable as global
+    binary="$(desktop_file_to_binary "$desktop")"
+
+    if [ -n "$BROWSER" ] && ([ "$scheme" = http ] || [ "$scheme" = https ]); then
+	    explain_browser_variable "$binary"
     fi
 
-    if [ -z "$(desktop_file_to_binary "$desktop")" ]; then
-        exit_failure_file_missing
+    if [ -z "$binary" ]; then
+        exit_failure_file_missing "Can't resolve a command for the given desktop file name"
     fi
 
     set_browser_mime "$desktop" "x-scheme-handler/$scheme"
@@ -903,6 +1000,11 @@ set_url_scheme_handler_generic()
 # }}} generic
 # }}} default protocol handler
 
+# Dispatches the given cli command to the correct handler
+# Expects global variables:
+# * op: "get", "check" or "set"
+# * parm: "default-web-browser" or "default-url-scheme-handler"
+# (handler_name, args ...)
 dispatch_specific()
 {
     local handler=$1; shift
